services:
  myflyitalyadsb:
    #build: ./
    image: ghcr.io/flyitalyadsb/myflyitalyadsb:latest
    container_name: myFlyitalyadsb
    restart: unless-stopped
    ports:
      - "84:84"
    command:
      - --server-listen
      - "0.0.0.0:84"
#      - --url-readsb
#     - "http://readsb_globe:30152/?all" uncomment and change it with your data source
      - --url-db
      - ${URL_DB}
    volumes:
      - ./deployment/db:/database #must be edited with your data (if you have chosen .sqlite)
      - ./deployment/json:/json #must be edited with your data
      - ./deployment/mlat:/mlat #must be edited with your data

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: ${NOME_DB}
      POSTGRES_USER: ${UTENTE_DB}
      POSTGRES_PASSWORD: ${PASSWORD_DB}
    ports:
      - "5433:5432"
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data

