services:
  myflyitalyadsb:
    build: ./
    container_name: myFlyitalyadsb
    restart: unless-stopped
    #volumes:
    #  - ${READSB_DATA_PATH}/json/ingest:/json
    ports:
     - "830:830"
     - "83:83"
    entrypoint: /usr/local/bin/python main.py
    command:
      - --server-listen
      - "0.0.0.0:830"
      - --deployment
      - --deployment-host
      - "0.0.0.0"
      - --deployment-port
      - "830"
    volumes:
      - ./deployment:/deployment