services:
  myflyitalyadsb:
    build: ./
    #image: ghcr.io/flyitalyadsb/myflyitalyadsb:latest
    container_name: myFlyitalyadsb
    restart: unless-stopped
    ports:
      - "830:830"
    entrypoint: /usr/local/bin/python main.py
    command:
      - --server-listen
      - "0.0.0.0:830"
    volumes:
      - ./deployment/db:/database
      - ./deployment/json:/json
      - ./deployment/dati:/dati
      - ./deployment/mlat:/mlat
