services:
  myflyitalyadsb:
    build: ./
    container_name: myFlyitalyadsb
    restart: unless-stopped
    ports:
     - "830:830"
    entrypoint: /usr/local/bin/python main.py
    command:
      - --server-listen
      - "0.0.0.0:830"
    volumes:
     - ./deployment/json:/json
     - ./deployment/dati:/dati
     - ./deployment/mlat:/mlat
